image: archlinux
packages:
  - r
  - linux-headers
  - texlive-core
  - texlive-fontsextra
  - texlive-formatsextra
  - texlive-science
  - texlive-bibtexextra
  - gcc-fortran
  - gcc-libs
secrets:
  - cb466cad-72fe-4083-9162-dcb2950df91b
sources:
  - https://git.sr.ht/~hckiang/glinvci
tasks:
  - setup: |
      Rscript -e 'dir.create(path = Sys.getenv("R_LIBS_USER"), showWarnings = FALSE, recursive = TRUE); install.packages(c("knitr","testthat","Rcgmin","lbfgsb3c","BB","ape","numDeriv","plyr"), repos="https://cloud.r-project.org", lib=Sys.getenv("R_LIBS_USER"))'
  - build: |
      R CMD build glinvci/
  - check: |
      R CMD check glinvci_*.tar.gz --as-cran
  - updatetarball: |
      mkdir tmpclone
      cd tmpclone
      GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@git.sr.ht:~hckiang/glinvci
      cd glinvci
      git checkout latest-tarballs
      cp ../../glinvci_*.tar.gz glinvci_latest_main.tar.gz
      git add glinvci_latest_main.tar.gz
      git commit -m'Updated latest tarball'
      GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git push origin latest-tarballs
